import React,{useEffect,useState} from 'react';
import {db} from './db';
import {totals} from './access';
const date=value=>value?new Intl.DateTimeFormat('es-CO',{timeZone:'America/Bogota',dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'Sin ingresos';
export default function Dashboard({profile,onStart,onResume,drafts,onDownload,busy,message,client=db}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[creating,setCreating]=useState(false),[notice,setNotice]=useState('');
 const admin=profile.rol==='admin';
 async function refresh(){setLoading(true);try{const r=await client.rpc('panel_actividad');if(r.error)throw r.error;setData(r.data);setError('');}catch(e){setError('No se pudo actualizar el panel: '+e.message);}finally{setLoading(false);}}
 useEffect(()=>{let alive=true;async function poll(){if(alive&&document.visibilityState==='visible')await refresh();}poll();const timer=setInterval(poll,30000);return()=>{alive=false;clearInterval(timer);};},[]);
 async function enable(e){e.preventDefault();const f=new FormData(e.currentTarget);setCreating(true);setNotice('');try{const r=await client.rpc('habilitar_encuestador',{p_codigo:f.get('codigo'),p_nombre:f.get('nombre')});if(r.error)throw r.error;setNotice('Encuestador habilitado. Puede entrar con su código y su propia contraseña.');await refresh();}catch(err){setNotice(err.message);}finally{setCreating(false);}}
 const sum=totals(data?.equipo||[]);
 return <><section className="card dashboard"><div className="dashboardhead"><div><span className="pill">{admin?'ADMINISTRACIÓN':'TRABAJO DE CAMPO'}</span><h2>{admin?'Panel de seguimiento':'Mis encuestas'}</h2><p>{admin?'Ingresos y producción del equipo.':'Cada entrevista queda asociada a tu código.'}</p></div><button onClick={onStart}>Iniciar encuesta →</button></div>
 <div className="metrics">{[['Completas','completas'],['Completas hoy','completas_hoy'],['Borradores','borradores'],['Cerradas incompletas','cerradas_incompletas']].map(([label,key])=><div key={key}><strong>{data?sum[key]:'—'}</strong><span>{label}</span></div>)}</div>
 <div className="refreshline"><span>{data?'Actualizado: '+date(data.actualizado):'Cargando registros…'} · actualización cada 30 s</span><button className="textbutton" disabled={loading} onClick={refresh}>Actualizar</button></div><p className="error" role="alert">{error}</p>
 {admin&&<><h3>Encuestas por persona</h3><div className="tablewrap"><table><thead><tr><th>Código / nombre</th><th>Rol</th><th>Completas</th><th>Hoy</th><th>Borradores</th><th>Cerradas incompletas</th><th>Último ingreso</th><th>Última actividad</th></tr></thead><tbody>{data?.equipo.map(e=><tr key={e.codigo}><td><b>{e.codigo}</b><small>{e.nombre||'Sin nombre'}{!e.activo?' · Inactivo':''}</small></td><td>{e.rol==='admin'?'Administrador':'Encuestador'}</td><td>{e.completas}</td><td>{e.completas_hoy}</td><td>{e.borradores}</td><td>{e.cerradas_incompletas}</td><td>{date(e.ultimo_ingreso)}</td><td>{date(e.ultima_actividad)}</td></tr>)}</tbody></table></div><p className="hint">Las cerradas incompletas incluyen rechazo de participación y filtro de elegibilidad. La última actividad no garantiza que la persona siga conectada.</p>
 <h3>Últimos ingresos</h3>{data?.ingresos.length?<div className="tablewrap"><table><thead><tr><th>Persona</th><th>Rol</th><th>Ingreso (Colombia)</th></tr></thead><tbody>{data.ingresos.map((i,n)=><tr key={n}><td>{i.codigo} {i.nombre}</td><td>{i.rol==='admin'?'Administrador':'Encuestador'}</td><td>{date(i.fecha)}</td></tr>)}</tbody></table></div>:<p>Todavía no hay ingresos registrados.</p>}<p className="hint">Últimas 100 sesiones exitosas desde esta versión de la aplicación. No incluye intentos fallidos ni ingresos antiguos.</p>
 <button className="secondary" disabled={busy} onClick={onDownload}>Descargar todas las encuestas CSV ↓</button></>}
 {drafts.length>0&&<section><h3>Mis borradores</h3><div className="draftlist">{drafts.map(d=><button className="secondary" key={d.client_id} onClick={()=>onResume(d)}>Retomar {d.id} · {d.zona_aplicacion}</button>)}</div></section>}
 <p role="status">{message}</p></section>
 {admin&&<details className="card onboarding"><summary>Habilitar un encuestador con acceso independiente</summary><p>1. En Supabase → Authentication → Users, crea una cuenta por persona. Para E002 usa <b>e002@encuestadores.invalid</b>, define una contraseña propia y marca Auto confirm user. Es un identificador técnico: no recibe correo.</p><p>2. Habilita aquí el mismo código. Entrega a la persona únicamente el código, su contraseña y el enlace de captura.</p><form onSubmit={enable}><label>Código<input name="codigo" placeholder="E002" pattern="[Ee][0-9]{3,}" maxLength={12} required/></label><label>Nombre del encuestador<input name="nombre" maxLength={100} required/></label><button disabled={creating}>Habilitar encuestador</button></form><p role="status">{notice}</p></details>}</>;
}
